"""store chunk metadata

Revision ID: 1216ada228a9
Revises: a11eb3965ab6
Create Date: 2026-09-30 15:57:28.592820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1216ada228a9'
down_revision: Union[str, Sequence[str], None] = 'a11eb3965ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('metadata', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'metadata')
    # ### end Alembic commands ###
