"""track document changes

Revision ID: 45e07a741ca6
Revises: 1216ada228a9
Create Date: 2026-09-30 18:32:07.583820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e07a741ca6'
down_revision: Union[str, Sequence[str], None] = '1216ada228a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "documents",
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=True,
        ),
    )

    op.add_column(
        "documents",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )

    op.execute(
        """
        UPDATE documents
        SET content_hash = encode(
            digest(content, 'sha256'),
            'hex'
        )
        """
    )

    op.alter_column(
        "documents",
        "content_hash",
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
