"""add chunk embeddings

Revision ID: d6f8407dfb7b
Revises: 0d99db11aa95
Create Date: 2026-10-03 18:31:07.117761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector.sqlalchemy
# revision identifiers, used by Alembic.
revision: str = 'd6f8407dfb7b'
down_revision: Union[str, Sequence[str], None] = '0d99db11aa95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
